name: Linux build
on: [push, pull_request]
jobs:
    random-build-name:
      runs-on: ${{ matrix.os }}
      timeout-minutes: 10
      strategy:
        matrix:
          python-version: [3.7, 3.8]
          os: [macOS-latest, ubuntu-latest, windows-latest]
      name: ${{ matrix.os }} py${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v2
        - uses: s-weigand/setup-conda@v1.0.5
          name: Setup Conda
          with:
            python-version: ${{ matrix.python-version }}
            conda-channels: anaconda, conda-forge
            activate-conda: true
        - name: Check versions
          run: |
            conda --version
            which python
            python --version
            pwd
            ls
        - name: Install dependencies
          run: |
            conda env update -n base --file=conda/environment.yml
            conda install pytest
        - name: Run tests
          run: |
            cd notebooks
            PYTHONPATH=. pytest
