name: Install/Update Analysis Cluster
on: 
  push:
    branches:
      - master
jobs:
  ornl-trigger-ansible:
    runs-on: ubuntu-20.04
    steps:
      - run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master -F "variables[PLAY]=${{ secrets.GITLAB_TRIGGER_PLAYBOOK }}" -F "variables[CONDA_ENV]=https://raw.githubusercontent.com/neutronimaging/python_notebooks/master/conda/environment.yml" ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
