name: Test and Deploy
on: [push, pull_request]
jobs:
    run-unit-tests:
      runs-on: ${{ matrix.os }}
      timeout-minutes: 10
      strategy:
        matrix:
          python-version: [3.7, 3.8]
          os: [macOS-latest, ubuntu-latest, windows-latest]
      name: ${{ matrix.os }} py${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v2
        - uses: s-weigand/setup-conda@v1.0.5
          name: Setup Conda
          with:
            python-version: ${{ matrix.python-version }}
            conda-channels: anaconda, conda-forge
            activate-conda: true
        - name: Check versions
          run: |
            conda --version
            which python
            python --version
            pwd
            ls
        - name: Install dependencies
          run: |
            conda env update -n base --file=conda/environment.yml
            conda install pytest
        - name: Run tests
          run: |
            cd notebooks
            PYTHONPATH=. pytest

    trigger-prod-deployment:
      if: ${{ github.ref == 'refs/heads/master' }}
      needs: run-unit-tests
      runs-on: ubuntu-20.04
      steps:
        - name: Update Conda Environment
          run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master -F "variables[PLAY]=${{ secrets.GITLAB_TRIGGER_PLAYBOOK }}" -F "variables[CONDA_ENV]=neutron-imaging" ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
        - name: Update Notebooks
          run: curl -sX POST -F token=${{ secrets.NOTEBOOKS_TRIGGER_TOKEN }} -F ref=master -F "variables[NOTEBOOKS_FOLDER]=IPTS_notebooks" ${{ secrets.NOTEBOOKS_TRIGGER_URL }} > /dev/null

    trigger-dev-deployment:
      if: ${{ github.ref == 'refs/heads/dev' }}
      needs: run-unit-tests
      runs-on: ubuntu-20.04
      steps:
        - name: Update Conda Environment
          run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master -F "variables[PLAY]=${{ secrets.GITLAB_TRIGGER_PLAYBOOK }}" -F "variables[CONDA_ENV]=neutron-imaging-dev" ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
        - name: Update Notebooks
          run: curl -sX POST -F token=${{ secrets.NOTEBOOKS_TRIGGER_TOKEN }} -F ref=master -F "variables[NOTEBOOKS_FOLDER]=IPTS_notebooks_testing" ${{ secrets.NOTEBOOKS_TRIGGER_URL }} > /dev/null
